---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flask-secret
  namespace: default
spec:
  encryptedData:
    SUPER_SECRET_KEY: AgBgqjma2qO5kMLt3suPmZXoZNqx2N4dJVZRJIxVoigioMcC+S4KXiqh1fA3bkiOUizCAeXDQNXzFrAVgU7QtbYUHhmlZkCPsM81cYi0McFMIRRjhqwKOUlpz9BsRA6xxXdmyXC5ubnyQDtHHjTR+Yg5novhl+NTs/TuSNbJG9cgjziMXOh9reFPaty3ePJ1ZUD+ODJParS2sxeCQ68x1j5RVo4xljcRPlGnVb5iPoZYn2I7t89uZ/uC94ZNo2C6HyC5zz7rFsKpKhYYviOIT+7/JZuD1s0iLi91Jn+D/SaZ6R8ckeR6qoZu7iRIbozP4RdiYKGxdCARavo5sTkQS4hD6HmLQMD7mmQH5mEviH26hDSpgDYKM2d20XLgs/7hBsMJk07z9tgE4qKzRKR0mZRoovkriZYn/HNrx88iKIzKjiTNGW5XJrz1ckM5TNuWHX1s49jULhHYh0XU36zXQCcDF/fUjuL5lIOeCEgQOqEv4Wqvlv3CdFYYpDpnNcFP1huq14nmXfEJ+WKLWJCBK8cqOY4gQH6Mdc03XlTaJqqzcI5YajaeU34A/QiRiEGRAFYJwpKLCKDDb/T+fOY1y2r07TAkZik5TXd13oZE1uxAXsoAqlIzV5l4SH8SU+IT8RkuofO+oYSBZVA5rfnw5natfJxNfr7wB+UIKXtHKp7rKOUWZPSFAUCfOE/7x+6yv/tC+hi9hGn6+e2TAvs=
  template:
    metadata:
      creationTimestamp: null
      name: flask-secret
      namespace: default
