image:
  repository: flask-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 5000
  targetPort: 5000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

envFromSecrets:
  - secretName: flask-secret
    keys:
      - SUPER_SECRET_KEY
  - secretName: my-secret  # This is the SOPS-managed secret
    keys:
      - ANOTHER_SECRET_KEY